version: '3.8'
services:
  service_event:
    container_name: service_event
    build: .
    environment:
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
      - kafka
    # networks:
    #   - service_event_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
     - "/var/lib/mongodb-event:/data/db"
    # networks:
    #   - service_event_network

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "events:1:1"
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - service_event_network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
#     networks:
#       - service_event_network

# networks:
#   service_event_network:
#     external: true
