version: '4.27.1'
services:
  service_event:
    container_name: service_event
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
     - "/var/lib/mongodb-event:/data/db"